-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Campaign"
(
    cf_id character varying COLLATE pg_catalog."default" NOT NULL,
    contact_id character varying COLLATE pg_catalog."default" NOT NULL,
    company_name character varying COLLATE pg_catalog."default",
    description character varying(200)[] COLLATE pg_catalog."default",
    goal real,
    pledged real,
    outcome character varying COLLATE pg_catalog."default",
    backers_count bigint,
    country character varying COLLATE pg_catalog."default",
    currency character varying COLLATE pg_catalog."default",
    launch_date date,
    end_date date,
    category_id character varying COLLATE pg_catalog."default" NOT NULL,
    subcategory_id character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Campaign_pkey" PRIMARY KEY (cf_id)
);

CREATE TABLE IF NOT EXISTS public."Category"
(
    category_id character varying COLLATE pg_catalog."default" NOT NULL,
    category character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Category_pkey" PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public."Contacts"
(
    contact_id character varying COLLATE pg_catalog."default" NOT NULL,
    first_name character varying COLLATE pg_catalog."default",
    last_name character varying COLLATE pg_catalog."default",
    email character varying COLLATE pg_catalog."default",
    CONSTRAINT "Contacts_pkey" PRIMARY KEY (contact_id)
);

CREATE TABLE IF NOT EXISTS public."Subcategory"
(
    subcategory_id character varying COLLATE pg_catalog."default" NOT NULL,
    subcategory character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Subcategory_pkey" PRIMARY KEY (subcategory_id)
);

ALTER TABLE IF EXISTS public."Campaign"
    ADD CONSTRAINT "Categories" FOREIGN KEY (category_id)
    REFERENCES public."Category" (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Campaign"
    ADD CONSTRAINT "Contacts" FOREIGN KEY (contact_id)
    REFERENCES public."Contacts" (contact_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Campaign"
    ADD CONSTRAINT "SubCategories" FOREIGN KEY (subcategory_id)
    REFERENCES public."Subcategory" (subcategory_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;